version: "3.8"
services:
  web:
    build: ./server
    image: YOUR_ACR_NAME.azurecr.io/talky-web:latest
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
  client:
    build: ./talky-app
    image: YOUR_ACR_NAME.azurecr.io/talky-client:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://web:8080