services:
  - type: web
    name: talky-backend
    env: python
    buildCommand: |
      apt-get update &&
      apt-get install -y portaudio19-dev python3-dev &&
      pip install -r requirements.txt
    startCommand: "python main.py"